name: 'Create ArgoCD application'
description: 'Create ArgoCD Application using cli'
inputs:
  name:
    required: true
    description: 'Application name'
  token:
    description: 'ArgoCD access token'
    required: true
  server:
    description: 'ArgoCD server'
    required: false
    default: argocd.dev.us-east-1.cond
  appNamespace:
    required: false
    description: 'Namespace to deploy application'
    default: argocd
  namespace:
    required: true
    description: 'Namespace to create resources'
  releaseName:
    required: false
    description: 'Helm release name'
    default: ''
  label:
    required: false
    description: 'Application label'
    default: 'purpose=qa'
  repo:
    required: true
    description: 'Helm chart repository'
  revision:
    required: true
    description: 'Helm chart repository revision | Chart version'
  path:
    required: false
    description: 'Path in repository to the app directory'
  chart:
    required: false
    description: 'Helm chart to deploy'
  values:
    required: false
    description: 'Helm values'
  ttl:
    required: true
    description: "K8s Janitor TTL"
  wait:
    required: false
    description: "Wait timeout in seconds"
    default: "1200"


runs:
  using: "composite"
  steps:
    - name: Install ArgoCD cli
      shell: bash
      run: |
        if [ -z $(which argocd || true) ]; then
          mkdir -p /home/runner/.local/bin/
          curl -o /home/runner/.local/bin/argocd https://artifactory.infra.us-east-1.conductor.sh/artifactory/thirdparty/argocd/v2.11.3/argocd-linux-amd64
          chmod +x /home/runner/.local/bin/argocd
        fi

    - name: cli parameters
      id: cli
      shell: bash
      run: |
        if [ -z "${{ inputs.chart }}" ]; then
          echo "chart=--path ${{ inputs.path }}" >> $GITHUB_OUTPUT
        else
          echo "chart=--helm-chart ${{ inputs.chart }}" >> $GITHUB_OUTPUT
        fi

    - name: Create Application
      shell: bash
      run: |
        cat <<EOT > "values-literal-file.yaml"
        ${{ inputs.values }}
        EOT
        cat "values-literal-file.yaml"

        echo "Creating application:"

        argocd app create ${{ inputs.name }} \
          --upsert \
          --auth-token '${{ inputs.token }}' \
          --server ${{ inputs.server }} \
          --insecure \
          --grpc-web \
          --annotations 'janitor/ttl=${{ inputs.ttl }}' \
          --label '${{ inputs.label }}' \
          --app-namespace ${{ inputs.appNamespace }} \
          --dest-server https://kubernetes.default.svc \
          --repo ${{ inputs.repo }} \
          --revision ${{ inputs.revision }} \
          ${{ steps.cli.outputs.chart }} \
          --sync-policy automated \
          --self-heal \
          --set-finalizer \
          --sync-option "Prune=true" \
          --sync-option "Replace=true" \
          --dest-namespace ${{ inputs.namespace }} \
          --release-name ${{ inputs.releaseName }} \
          --values-literal-file values-literal-file.yaml

    - name: Wait for App is synced and ready
      shell: bash
      run: |
        timeout ${{ inputs.wait }}s bash -c '
          EXIT_CODE=20
          while [[ ${EXIT_CODE} -ne 0 ]];
          do
            argocd app wait ${{ inputs.name }} --timeout 30 \
              --auth-token '${{ inputs.token }}' \
              --server ${{ inputs.server }} \
              --insecure \
              --grpc-web
            EXIT_CODE=$?
          done'
